import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import Message from '@/models/Message';

/**
 * GET /api/messages
 * Fetch all messages for the admin inbox, sorted by newest first.
 */
export async function GET() {
  try {
    await dbConnect();

    const messages = await Message.find({})
      .sort({ createdAt: -1 })
      .lean();

    return NextResponse.json(messages, { status: 200 });
  } catch (error) {
    console.error('Error fetching messages:', error);
    return NextResponse.json(
      { error: 'Failed to fetch messages' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/messages
 * Accept submissions from the public Contact Us page.
 * Saves with default status of 'New'.
 * Ticket number is auto-generated by the pre-save hook.
 */
export async function POST(request: NextRequest) {
  try {
    await dbConnect();

    const body = await request.json();

    // Validate required fields from the Contact Us form
    const { name, email, subject, messageBody } = body;

    if (!name || !email || !subject || !messageBody) {
      return NextResponse.json(
        {
          error: 'Missing required fields',
          details: 'name, email, subject, and messageBody are required.',
        },
        { status: 400 }
      );
    }

    // Basic email format validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email address format' },
        { status: 400 }
      );
    }

    const message = await Message.create({
      name,
      email,
      phone: body.phone || undefined,
      subject,
      messageBody,
      source: body.source || 'Contact Form',
      relatedProgram: body.relatedProgram || undefined,
      // status defaults to 'New' via schema
      // ticketNumber auto-generated via pre-save hook
    });

    return NextResponse.json(
      { message: 'Message sent successfully', data: message },
      { status: 201 }
    );
  } catch (error) {
    console.error('Error creating message:', error);

    // Handle Mongoose validation errors
    if (error instanceof Error && error.name === 'ValidationError') {
      return NextResponse.json(
        { error: 'Validation failed', details: error.message },
        { status: 400 }
      );
    }

    return NextResponse.json(
      { error: 'Failed to send message' },
      { status: 500 }
    );
  }
}
